name: CI/CD Pipeline - Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run Docker Compose
        run: make up-detached
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jayplus-dev-artifact
          path: ./
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jayplus-dev-artifact
          path: /home/runner/work/jayplus/jayplus-dev-artifact
      - name: Setup SSH and Deploy
        run: |
          sudo apt-get install -y openssh-client
          mkdir -p ~/.ssh
          ssh-keyscan 178.128.228.63 >> ~/.ssh/known_hosts
          # Start the ssh-agent in the background
          eval "$(ssh-agent -s)"
          # Add the SSH key with passphrase to the ssh-agent
          echo "${{ secrets.GH_ACTIONS_DEV_SSH_PASSPHRASE }}" | ssh-add - <<< "${{ secrets.GH_ACTIONS_DEV_SSH_KEY }}"
          # Deployment using SCP and SSH
          scp -r -i gh-actions-dev-ssh-key /home/runner/work/jayplus/jayplus-dev-artifact/* gh-actions@178.128.228.63:~/
          ssh -i gh-actions-dev-ssh-key gh-actions@178.128.228.63 "cd ~/ && make up-detached"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
